FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.19.1

FROM alpine:latest
RUN apk add --no-cache postgresql-client
COPY --from=builder /go/bin/goose /usr/local/bin/goose
WORKDIR /app
